- lib/orogen/templates/typekit/Plugin.cpp
This commit synchronizes the reported typekit names
in RTT with the typekits names written down in the
pkgconfig files for the deployments.
> Renamed reported typekit names from "/orogen/<foo>" to "<foo>".

- lib/orogen/templates/main.cpp
This fixed issue https://github.com/orocos-toolchain/orogen/issues/47
The macos struct looks diffently than the linux one, use memset instead.
Also include string.h explicitly even std::string
is alredy used in this class.
It fixes #47
> main deployment: initialize SIGINT handler differently.

- lib/orogen/templates/tasks/TaskBase.hpp
DO NOT MERGE: this will break the compilation of existing components (missing headers) so we'll have to give enough advance warning on the ML. Plus, there seem to currently have some issues in the generated code.
The main change is to remove the inclusion of the all-encompassing Types.hpp header in TaskBase.hpp
This saves both CPU time and memory during the build. On
control/orogen/auv_control, which only imports the 'base' typekit,
we save on my (very old Core 2 Duo) machine 1min 20s and 250M of
memory (benchmark done with -j1). On -j4, this would mean roughly
1G of memory.
In addition, it avoids unnecessarily rebuilding task files. The
Types.hpp headers include all types of a typekit, as well as the
imported typekits, which means that we currently MUST rebuild all
task files as soon as …
> merge date 10.06.2015: Streamline headers included in task base

- lib/orogen/loaders/base.rb
- lib/orogen/spec/deployment.rb
- lib/orogen/spec/project.rb
Calling #inspect on anything that was containing a Project or loader
was leading to pages and pages of text. Make it a lot simpler.
> explicitely define #inspect on some classes

- Rakefile
Fixes the following warning when running rake: 
WARN: cannot load the Hoe gem, or Hoe fails. Publishing tasks are disabled
WARN: error message is: undefined local variable or method `hoe_spec' for main:Object
> Fix setting of test suite in Rakefile

- lib/orogen/loaders/base.rb
Some methods (namely, the ones that do opaque-related resolutions)
query imported typekits for types, which in turn return types from
the typekit's registry, not the loader's
Resolve the type locally to fix this.
> loader: ensure that type-resolution methods return a type from the receiver's registry

- lib/orogen/gen/deployment.rb
- lib/orogen/spec/deployment.rb
This really is a specificity of the C++ code generator. Defining a
deployment that has an abstract task is not a problem. Instanciating
it (i.e. trying to run it) is / might be.
> spec: move the test on abstract? to the codegen part

- lib/orogen/gen/templates.rb
This is needed, if a plugin wants to render a template.
> templates: Allow passing of absolute path to template file

- lib/orogen/gen/tasks.rb
- lib/orogen/gen/typekit.rb
- lib/orogen/spec/configuration_object.rb
- lib/orogen/templates/tasks/tasks.pc
ValueSet is on the way out, and was really unneeded here.
For more information, https://github.com/orocos-toolchain/utilrb/pull/28
> replace ValueSet by Set

- lib/orogen/loaders/base.rb
- lib/orogen/loaders/pkg_config.rb
- lib/orogen/spec/typekit.rb
As stated in both commits, this really should have very little impact on the load times of actual applications, but speeds up Syskit test suites tremendously (110s to 85s)
> Improve reload performance

- lib/orogen/gen/typekit.rb
Forwarding the defines is necessary because the clang importer needs them to parse some headers correctly.
> typekit.rb: forward compiler defines when loading types

- lib/orogen/gen/typekit.rb
- lib/orogen/spec/typekit.rb
Currently opaque type equality is checked using the == operator which calls `do_compare` in typelib. And I guess that it is intentional that it checks for equal member types and offsets and doesn't check the name of the type.
But in the case two opaques are defined having the same members. E.g.:
```
struct ClassAWrapper
{
std::vector<uint8_t> bin;
};
struct ClassBWrapper
{
std::vector<uint8_t> bin;
};
```
they currently both resolve in the same opaque type ClassA.
So I think comparing the type name instead of the type would be the right thing to do here.
> opaque type equality should be checked by typename instead of type member equality

- lib/orogen/gen/typekit.rb
The code was using exist? to check for a file's existence, but we support only
files so use file? instead.
> typekit: be stricter when looking for files to import

- .gitignore
- lib/orogen.rb
- lib/orogen/gen/deployment.rb
- lib/orogen/loaders/base.rb
- lib/orogen/loaders/pkg_config.rb
- lib/orogen/spec/typekit.rb
- lib/orogen/templates/typekit/typelib/transport-typelib.pc
- lib/orogen/test.rb
- test/fixtures/pkgconfig_loader/typekit/not_exporting.tlb
- test/fixtures/pkgconfig_loader/typekit/not_exporting.typelist
- test/loaders/test_pkg_config.rb
This pull request removes the two main caches that were present, related to orogen loading
- the XML parsing cache
- the PkgConfig package cache
It depends on https://github.com/orocos-toolchain/utilrb/pull/30.
https://github.com/rock-core/tools-orocosrb/pull/94 *must* be applied at the same time, as some private APIs of Loaders::PkgConfig is used by Orocos::Process.
These two caches were meant to work around bad orogen loading behaviour in the pre-loaders days, that is the fact that orogen had a tendency to load the same package over and over again. This has been fixed by the orogen loaders.
Their side effect - and why I remove them - was that we ended up with more than 250k objects in the Ruby heap in a typical Syskit application, that were only related to these - and never used. That's …
> Remove caches

- misc/new_project/NAME.orogen
IMO this template orogen file should import 'std' since it is used in the ports.
Otherwise when executing:
$ orogen create example && cd example
$ orogen example.orogen
The orogen parser reports:
===== Internal error =======
Please report the following error to the orogen developers
~/dev/tools/orogen/lib/orogen/gen/typekit.rb:2189:in `include_for_type': while rendering tasks/TaskBase.hpp: no includes known for /int32_t defined in [] (OroGen::InternalError)
> missing std to parse this orogen file

- lib/orogen/loaders/base.rb
- lib/orogen/test.rb
- test/loaders/test_base.rb
The right solution, and one I hope someone will one day have
the time to implement, would be to store it at generation time.
In the meantime, use it in loaders to avoid attempting complex
resolutions over and over and over again.
> loaders: use metadata to store opaque information on load

- lib/orogen/spec/configuration_object.rb
- lib/orogen/spec/port.rb
- lib/orogen/templates/main.cpp
Finally removing a little bit of horrible ugliness.
Must be merged at the same time than rock-core/tools-orocosrb#104
> load the RTT typekit after the std typekit so that orocos_type_name = typelib_type_name

- lib/orogen/templates/tasks/tasks.pc
- lib/orogen/templates/typekit/CMakeLists.txt
Trying to clean the autogenerated pkgconfig files a bit, since the pc files generated by orogen currently contain redundant flags and also quoted flags (is there really a need for the quoting?)
> Recude redundant flags pkgconfig files

- lib/orogen/templates/typekit/package.xml
This is necessary because an empty license tag is not valid. When trying to build a package that's using this template unmodified, catkin aborts with an error message saying that a license tag cannot be empty or contain only whitespace. This breaks the compilation of the ROS-Rock-bridge at the moment.
> Fill empty license tag in package.xml template

- lib/orogen/templates/tasks/TaskBase.cpp
avoids conflict with global and nested namespace for the task
> Added missing global operator

- lib/orogen/gen/typekit.rb
This makes orogen eventually pass cflags to typegen. This was discussed at orocos-toolchain/typelib#99 when thinking about how to tell typegen which cpp copiler version to use (eg. `-std=c++11`).
> Forward cflags of loaded headers files to load options

- lib/orogen/gen/typekit.rb
Reverts orocos-toolchain/orogen#95. Wrong button
> Revert "Forward cflags of loaded headers files to load options"

- lib/orogen/exceptions.rb
- lib/orogen/gen/tasks.rb
- lib/orogen/loaders/aggregate.rb
- lib/orogen/loaders/base.rb
- lib/orogen/loaders/files.rb
- lib/orogen/loaders/pkg_config.rb
- lib/orogen/spec/configuration_object.rb
- lib/orogen/spec/dynamic_ports.rb
- lib/orogen/spec/operation.rb
- lib/orogen/spec/port.rb
- lib/orogen/spec/task_context.rb
- test/loaders/test_aggregate.rb
- test/loaders/test_base.rb
- test/loaders/test_pkg_config.rb
- test/spec/test_task_context.rb
The code for this was present in orocos.rb, but it's really an orogen-pkgconfig-specific code. Move
the functionality here to keep it close to orogen itself.
> Expose library path resolution code into loaders

- lib/orogen.rb
- lib/orogen/gen/project.rb
- lib/orogen/loaders/rtt/OCL.orogen
- lib/orogen/spec/project.rb
- lib/orogen/spec/task_context.rb
- lib/orogen/warn_deprecated.rb
- test/spec/test_task_context.rb
This fixes a longstanding problem between subclassing and plugins. Plugins are executed after the
TaskContext creation, but before the `subclass` statement. This means that they are not aware of
interface objects (properties, ports ...) that would be there because of the parent task context.
For instance, This leads to duplicate properties in the `orogen_metadata` plugin
> pass subclass at task context creation

- manifest.xml
The typo makes rosdep fail: https://github.com/ros-infrastructure/rosdep/issues/575
> Fix typo in manifest.xml

- bin/orogen
`orogen` would display the whole exception (flagging the error as internal) instead of showing a proper error message.
> fix error reporting when a type is not found

- manifest.xml
- package.xml
Follow-up on #111 (@NikolausDemmel).
Unfortunately the old format 1 of the ROS package manifest (`manifest.xml`) differentiates between ROS packages and third-party software provided by the operating system and managed by [rosdep](http://wiki.ros.org/rosdep): http://docs.ros.org/independent/api/rospkg/html/manifest_xml.html
Because `rake` and `ruby` are system dependencies and do not provide a ROS-compatible package manifest, the "correct" way to list them in `manifest.xml` would be
```xml
<rosdep name="ruby" />
<rosdep name="rake" />
```
The patch in #111 fixes the `InvalidManifest` exception, but [rosdep](http://wiki.ros.org/rosdep) is still not able to resolve and install the dependencies:
```
johannes@im-laptop-007:/opt/orocos/kinetic/src/orocos_toolchain$ rosdep install --from-path . …
```
> Fix manifest.xml rosdep compatibility

- lib/orogen/gen/imports.rb
- lib/orogen/gen/project.rb
- lib/orogen/gen/templates.rb
- lib/orogen/gen/typekit.rb
- lib/orogen/marshallers/corba.rb
- lib/orogen/templates/typekit/corba/CMakeLists.txt
- lib/orogen/templates/typekit/corba/transport-corba.pc
Build tests added by:
We generate one IDL file per typekit, which means that include paths should be transitive. The current code was using `#used_typekits`, which only computes the typekits that the types exported by the typekit need.
Let's assume typekit [X](https://github.com/rock-core/build_tests-orogen-typekit_idl_cross_dependency_regression_1/blob/master/typekit_idl_cross_dependency_regression_1Types.hpp) defines type `BaseUsingStruct` and `StdUsingStruct`. `BaseUsingStruct` reuses a type already defined by typekit `base`. `StdUsingStruct` reuses a type already defined by typekit `std`.
Now, we have typekit [Y](https://github.com/rock-core/build_tests-orogen-typekit_idl_cross_dependency_regression_2/blob/master/typekit_idl_cross_dependency_regression_2Types.hpp) which defines …
> fix include path used during IDL generation in some recursive cases

- lib/orogen/gen.rb
- lib/orogen/gen/deployment.rb
- lib/orogen/gen/project.rb
- lib/orogen/spec.rb
- lib/orogen/spec/deployment.rb
- lib/orogen/spec/task_context.rb
- lib/orogen/templates/config/Deployment.cmake
- lib/orogen/templates/main.cpp
- lib/orogen/templates/tasks/CMakeLists.txt
This may be used for any library that need a one-time initialization
in main. So far, orogen had only support for Qt. I needed this for
instance for GStreamer.
This is tested against Qt4 and GStreamer.
> gen: implement generic global initializer support for deployments

- lib/orogen/gen/typekit.rb
- test/gen/test_typekit.rb
This happens if for example Vector<Foo *> is given as opaque.
Extracted from #89 with added tests
> fix return value of method_name in case typename contains a *

- lib/orogen/gen.rb
- lib/orogen/templates/main.cpp
The current implementation was just ... wrong. It probably was crashing things as soon as components were reconfigured (and sometimes at startup as well).
Tested through gui/orogen/qt_base (https://github.com/rock-core/rock.build-tests-buildconf/pull/9)
> fix the Qt global initializer

- lib/orogen/gen/base.rb
[CMake Policy 0023](https://cmake.org/cmake/help/latest/policy/CMP0023.html) states that:
"Plain and keyword target_link_libraries() signatures cannot be mixed."
Therefore this change permits the keyword use when needed through context.
> gen: allow to set the cmake keyword to target_link_libraries

- lib/orogen/gen/typekit.rb
- test/data/typekit/remove_types.h
- test/gen/test_typekit.rb
The current implementation of type_export_policy only deals
with type *exports*, i.e. the RTT side of things. All types
within the imported headers are still processed, saved in the
tlb files and conversion methods (to e.g. CORBA) are generated
for them. This is so as the RTT side is the one that is really
heavy in compilation time and binary size.
However, there are some cases where types may be incompatible
with the conversion. For instance, CORBA forbids any identifier
to match a keyword. It's easy to modify when one controls said
header, but if (1) we don't control the header and (2) the header
contains both the offending type and types that *are* needed, we
ended up in a broken situation.
This new method allows to explicitly remove the problematic type(s)
even if they were imported.
> gen: implement Typekit#remove_types

- manifest.xml
- package.xml
… such that it can be installed correctly by [rosdep](https://wiki.ros.org/rosdep):
**Without this patch**:
```sh
$ rosdep install -y --from-path . --ignore-src
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
orogen: Missing resource metaruby
ROS path [0]=/build/orocos_toolchain
```
**With this patch** (on Ubuntu 18.04):
```
$ rosdep install -y --from-path . --ignore-src
executing command [sudo -H gem install metaruby]
Fetching: rexml-3.2.4.gem (100%)
Successfully installed rexml-3.2.4
Fetching: kramdown-2.3.0.gem (100%)
Successfully installed kramdown-2.3.0
Fetching: utilrb-3.1.0.gem (100%)
Successfully installed utilrb-3.1.0
Fetching: metaruby-2.0.0.gem (100%)
Successfully installed metaruby-2.0.0
Parsing documentation for …
```
> manifest.xml: switch metaruby to tag type <rosdep>
